# Generated by Django 5.2.10 on 2026-02-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_content_options_alter_content_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(verbose_name='контент'),
        ),
    ]
