# Generated by Django 5.2.10 on 2026-02-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_content_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='имя')),
                ('phone', models.CharField(max_length=255, verbose_name='телефон')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='e-mail')),
                ('note', models.TextField(blank=True, max_length=255, null=True, verbose_name='комметарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('is_active', models.BooleanField(default=False, verbose_name='Обрабатана?')),
            ],
            options={
                'verbose_name': 'обратная связь',
                'verbose_name_plural': 'обратная связь',
                'ordering': ['-created_at'],
            },
        ),
    ]
